/*
 * Each parameter values can be changed in order to
 * set base style to the travelgraph.
 * This style is setted througth the travelgraph-js-object
 * an is used to scale the graph elements
 */

/**
 *
 *
 *@namespace
 * @author Cem Akpolat
 */
weatherConfig={
    type:{
           'CLEAR':
           {
               icon:"wi-day-sunny",
               title:"Clear"
           },
           'CLOUDS':
           {
               icon:"wi-day-cloudy",
               title:"Clouds"
           },
           'DRIZZLE':
           {
               icon:"wi-day-sleet",
               title:"Drizzle"
           },
           'EXTREME':
           {
               icon:"extreme",
               title:"Extreme"
           },
           'RAIN':
           {
               icon:"wi-day-rain",
               title:"Rain"
           },
           'SNOW':
           {
               icon:"wi-day-snow",
               title:"Snow"
           },
           'THUNDERSTORM':
           {
               icon:"wi-day-thunderstorm",
               title:"Thunderstorm"
           },
           'UNDEFINED':
           {
               icon:"undefined",
               title:"Undefined"
           },
           'ADDITIONAL':
           {
               icon:"additional",
               title:"Additional"
           },
           'ATMOSPHERE':
           {
               icon:"atmosphere",
               title:"Atmosphere"
           }
       }
};
 tgConfig =
		{
			popup:
				{
					 'item':
					 	{
                            'Car2Go':
                            {
                                icon:"icon-my-car",
                                color:"#E29A34",
                                mapcolor:"#E29A34"
                            },
							'PEDESTRIAN':
								{
									icon:"icon-walk",
                                    color:"#A1B744",
									mapcolor:"#A1B744"
								},
							'CAR':
								{
									icon:"icon-my-car",
									color:"#E06F36",
									mapcolor:"#E06F36"
								},
                            'CAR_SHARING':
                                {
                                    icon:"icon-my-car",
                                    color:"#E29A34",
                                    mapcolor:"#E29A34"
                                },
							'UBAHN':
								{
									icon:"icon-opvn",
                                    color:"#9E8A33",
                                    mapcolor:"#9E8A33"
								},
							'SBAHN':
								{
									icon:"icon-opvn",
                                    color:"#9E8A33",
                                    mapcolor:"#9E8A33"
								},
							'TRAM':
								{
									icon:"icon-opvn",
                                    color:"#9E8A33",
                                    mapcolor:"#9E8A33"
								},
							'BUS':
								{
									icon:"icon-opvn",
									color:"#9E8A33",
                                    mapcolor:"#9E8A33"
								},
                            'REGIONAL_TRAIN':
                                {
                                    icon:"icon-opvn",
                                    color:"#9E8A33",
                                    mapcolor:"#9E8A33"
                                },
							'BICYCLE':
								{
									icon:"icon-bicycle",
									color:"#CC5E50",
									mapcolor:"#CC5E50"
								},
                            'BICYCLE_SHARING':
                                {
                                    icon:"icon-bicycle",
                                    color:"#C4486B",
                                    mapcolor:"#C4486B"
                                },
                            'TAXI':{
                                    icon:"icon-taxi",
                                    color:"#4C9794",
                                    mapcolor:"#4C9794"
                                },
							'DEFAULT':
								{
									icon:"o",
									color:"lightskyblue",
									mapcolor:"lightskyblue"
								},
                            'undefined':
                                {
                                    icon:"o",
                                    color:"#9E8A33",
                                    mapcolor:"#9E8A33"
                                }
					 	}//endof .item
				}//endof popup
		};//endof tgConfig